# Generated by Django 5.2 on 2025-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanImmDB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoleculeClinicalRecord',
        ),
    ]
