# Generated by Django 5.2 on 2025-04-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanImmDB', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicaltrials',
            options={'managed': False},
        ),
    ]
